### ISSUE TITLE
Extend VoxEngine.easyProcess with handlers

### ISSUE THREAD

**Issue by alevgenk** [voximplant/easyprocess#4]
It might be useful to extend easyProcess() and add new parameters for handlers such as **call1HangupHandler** and **call2HangupHandler** to process some custom logic.

**Comment by NikolasMelui** [comment]
Hi there! Thx for the issue!
The essence of an `easyProcess` is to keep it easy :slightly_smiling_face:  And precisely so that you can extend it as you like, we made it open source. Just copy the source code, modify it, and use it in your scenario instead of `VoxEngine.easyProcess`.

**Comment by alevgenk** [comment]
> Hi there! Thx for the issue! The essence of an `easyProcess` is to keep it easy 🙂 And precisely so that you can extend it as you like, we made it open source. Just copy the source code, modify it, and use it in your scenario instead of `VoxEngine.easyProcess`.

Hi! 
Just did as you wrote.
But if the original source code of easyProcess will be significally changed, it can lead to some implicit issues.

Anyway, thanks for an answer. Let's close this issue.

**Comment by NikolasMelui** [comment]
Just take a look at the commit history and rest assured that there is nothing to worry about 😁
